import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";

const outfitFont = Outfit({

  subsets: ["latin"],
});



export const metadata = {
  title: "AI-Generated Art Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outfitFont.className} h-full antialiased`}
    >
      <body >
        <Navbar></Navbar>
        <main className="max-w-7xl mx-auto">
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
